### ISSUE TITLE
online converter and support for filters

### ISSUE THREAD

**Issue by surli** [sbraconnier/jodconverter#118]
Does the online converter support custom filters? It looks like the API is not available. 

```
OnlineConverter onlineConverter = OnlineConverter.builder()
            .officeManager(officeManager)
            .formatRegistry(JsonDocumentFormatRegistry.create(docFormatInput))
            .filterChain(new LinkedImagesEmbedderFilter())
            .build();
```

**Comment by sbraconnier** [comment]
No. The online converter is only a client sending requests to LibreOffice Online, using the same "API" as the local converter. This module (online) does not require a local office installation.

Since LibreOffice Online does not support such customization (filters), the jodconverter-online module can't support it either.

**Comment by surli** [comment]
Thanks for the quick answer.
Are you aware of any plan to move towards this direction on LO side?

**Comment by sbraconnier** [comment]
I don't think they are I'm afraid. But if your goal is to ensure that a conversion request returns a document with all the images embedded, I think you could open a ticket to LibreOffice.

I had a [similar problem](https://bugs.documentfoundation.org/show_bug.cgi?id=117077) while converting to HTML and they changed the default behavior for online conversion.

**Comment by surli** [comment]
Good to know, thanks for the hint.
