### ISSUE TITLE
some class can't find from the maven jar

### ISSUE THREAD

**Issue by CodeloveCode** [sbraconnier/jodconverter#14]
I get the jar from maven:
<pre>
<dependency>
  <groupId>org.jodconverter</groupId>
  <artifactId>jodconverter-core</artifactId>
  <version>4.0.0-RELEASE</version>
</dependency>
</pre>
    But i can't find the class below:DefaultOfficeManager ,DocumentConverter  etc,whether it need to be updated?
![qq 20170713110934](https://user-images.githubusercontent.com/13723906/28148838-d1c46b56-67bb-11e7-83a4-18446fc841fc.png)

**Comment by sbraconnier** [comment]
You are totally right!

Those classes were not in the 4.0.0-RELEASE. Please refer to the [v4.0.0](https://github.com/sbraconnier/jodconverter/tree/v4.0.0) tag for the complete content of the 4.0.0 version available through Maven.

The trunk needs more robust tests in order to be release as a version. The next version will be 4.1.0 and should be release in a week or so.

In the meantime, you can build the project yourself if you still want to use the new way JodConverter can be used ([using a DefaultOfficeManager and DefaultConverter](https://github.com/sbraconnier/jodconverter/blob/master/doc/usage/java-library.md)), but there is no guarantee that there will be no breaking changes.

**Comment by CodeloveCode** [comment]
I got it .
I'll do it  in the traditional way ,thank you so much!

**Comment by enigma969** [comment]
I have the same problem, but don't know how to refer to the v4.0.0 tag in Maven? 

I use: 
```
<dependency>
  <groupId>org.jodconverter</groupId>
  <artifactId>jodconverter-core</artifactId>
  <version>4.0.0-RELEASE</version>
</dependency>
```

And I don't want to use Gradle. 

Thanks for your help!

**Comment by sbraconnier** [comment]
Not sure I understand what is your problem exactly. If you are looking for an example using the v4.0.0 version, [since the trunk contains new classes](https://github.com/sbraconnier/jodconverter/issues/14#issuecomment-314980390), here it is:

```java
File inputFile = new File("document.doc");
File outputFile = new File("document.pdf");

// Create an office manager using the default configuration.
// The default port is 2002.
OfficeManager officeManager = new DefaultOfficeManagerBuilder().build();
try {

    // Start an office process and connect to the started instance (on port 2002).
    officeManager.start();

    // Convert
    OfficeDocumentConverter converter = new OfficeDocumentConverter(officeManager);
    converter.convert(inputFile, outputFile);
} finally {
    // Stop the office process
    officeManager.stop();
}
```

If this doesn't answer to your question, please add more details.

**Comment by enigma969** [comment]
Thanks! I'm able to import these classes.
