### ISSUE TITLE
How to convert a ppt to multiple png files

### ISSUE THREAD

**Issue by gawaine1988** [sbraconnier/jodconverter#192]
I have a question,  I can use the following code to translate a ppt to pdf：
```
OnlineOfficeManager make = OnlineOfficeManager.make("http://localhost:9980/");
        try {
            make.start();
            OnlineConverter build = OnlineConverter
                    .builder()
                    .officeManager(make)
                    .formatRegistry(DefaultDocumentFormatRegistry.getInstance())
                    .build();


            File localOfficeFile = new File(word.getLocalPath());
            File targetFile = new File(getTargetPdfPath(word.getLocalPath()));
            build.convert(localOfficeFile)
                    .to(targetFile)
                    .execute();
            make.stop();
            return "testTargetPdfPath";
        } catch (OfficeException e) {
            throw new RuntimeException("Convert error!");
        }
```
But when I  use this code to translate ppt to png, it only convert  the first page. 

How can I transform the ppt to mutiple png

**Comment by sbraconnier** [comment]
May I ask which "Online" server is running when you do that ??

I'm afraid there is no way to do that at the moment using a `OnlineOfficeManager`. [LibreOffice Online](https://www.libreoffice.org/download/libreoffice-online/) will not support that, and [the sample project](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest) showing how to create a server that looks like LibreOffice Online does not support this either. But the sample project may be updated in order to be able to receive parameters that would support known [filters](https://github.com/sbraconnier/jodconverter/wiki/Using-Filters)

**Comment by sbraconnier** [comment]
Feel free to re-open if I didn't answer properly.
