### ISSUE TITLE
Do conversions on remote host with LibreOffice directly (not with LibreOffice online, not through spring boot)

### ISSUE THREAD

**Issue by diMANiac** [sbraconnier/jodconverter#195]
So, the issue is to have the functionality to connect to LibreOffice, which is launched on remote host. Not to LibreOffice Online and not passing documents through spring-boot application on that remote host which will manage "local" office. 

Some say, that uno library allows that.

There's hardcoded "host=127.0.0.1" in org.jodconverter.office.OfficeUrl#socket, so, theoretically, we could pass host as a parameter to ExternalOfficeManager and somehow connect to remote office and do conversions with it?

**Comment by DmitryMishchuk** [comment]
Guess my issue should also go here:
Trying to connect to dockerized LibreOffice to convert some xlsx to pdf is a failure. The connection simply hangs and gets disconnected due to timeout, where as if I go and trigger container with direct office command it works as expected outputting a transformed document.

**Comment by sbraconnier** [comment]
@DmitryMishchuk May I ask if the docker file is public or if not, is it possible for you to share it??

**Comment by sbraconnier** [comment]
It will be possible in the next release, thanks to PR #241
