### ISSUE TITLE
Temporary file name added in CSV -> PDF conversion

### ISSUE THREAD

**Issue by nirav-patel** [sbraconnier/jodconverter#219]
Hi @sbraconnier, I am facing issue while converting any CSV file to PDF using jodconverter. 

Original CSV File:
![image](https://user-images.githubusercontent.com/5373143/87653202-d6132700-c772-11ea-85f1-2d1938e8405c.png)

After PDF conversion: (Check temporary source file name added tempfile_166). Also date conversion on 1st column is not proper. 
![image](https://user-images.githubusercontent.com/5373143/87653361-0bb81000-c773-11ea-8954-d3ea6b80663c.png)

Here, temporary file name got added on each PDF page as shown in above image. 

Using following versions:
```
jodconverter-local: 4.3.0
LibreOffice: 6.4.4
spring-boot 2
```

Can you please take a look why such temporary file name added?

Thanks,
Nirav

**Comment by sbraconnier** [comment]
Hi there,

Could you please first try to open the file WITHOUT jodconverter and try an "export as pdf" manually? Let me know if the result is the same or not. To resolve this, we need to know first if it is a jodconverter issue or a LibreOffice one. If it is an issue with LibreOffice, we need to know if LibreOffice support this, and which settings are required.

**Comment by nirav-patel** [comment]
Hi @sbraconnier Thanks for the quick response. 

I tried exporting original CSV file to PDF and it also displays file name on page header, so looks like LibreOffice issue.
Though I have noticed that dates exported to PDF properly as you can see in below screenshot. Using jod-converter, it displayed XXX for some reason as shown in previous comments. 
![image](https://user-images.githubusercontent.com/5373143/87762668-1f29b080-c831-11ea-8b11-ba5b8d103a7a.png)

Regarding filename as header, possibly some tweaks in LibreOffice settings may require.

**Comment by sbraconnier** [comment]
Thanks!!! Could you please share your CSV so I could look into this using the same file as you (please remove all sensitive data first!)... Thanks!

**Comment by nirav-patel** [comment]
I have attached sample CSV file. 
[sample_csv.zip](https://github.com/sbraconnier/jodconverter/files/4945724/sample_csv.zip)

Thanks!

**Comment by is-simon** [comment]
Strange, I didn't have the same problem as you, but the date column was different. Maybe you could take a look [here](https://ask.libreoffice.org/en/question/11333/is-it-possible-to-specify-csv-filter-options-on-the-command-line/) and try to find the proper [Filter Options for the CSV Filter](https://wiki.openoffice.org/wiki/Documentation/DevGuide/Spreadsheets/Filter_Options) that would work for you. The default one used by jodconverter is "44,34,0". The way I succeed to have a date column the same as you was by setting the column format to "TEXT", like this:
```java
converter
        .convert(new File("C:\\temp\\sample_csv\\\\sample_csv\\sample_csv.csv"))
        .as(DocumentFormat.builder()
                .from(DefaultDocumentFormatRegistry.CSV)
                .loadProperty("FilterOptions", "44,34,0,1,1/2")
                .build())
        .to(new File("C:\\temp\\sample_csv\\out.pdf"))
        .execute();
```
You may want to cache the created DocumentFormat instead of creating a new one for each conversion.

**Comment by sbraconnier** [comment]
Strange, I didn't have the same problem as you, but the date column was different. Maybe you could take a look [here](https://ask.libreoffice.org/en/question/11333/is-it-possible-to-specify-csv-filter-options-on-the-command-line/) and try to find the proper [Filter Options for the CSV Filter](https://wiki.openoffice.org/wiki/Documentation/DevGuide/Spreadsheets/Filter_Options) that would work for you. The default one used by jodconverter is "44,34,0". The way I succeed to have a date column the same as you was by setting the column format to "TEXT", like this:
```java
converter
        .convert(new File("C:\\temp\\sample_csv\\\\sample_csv\\sample_csv.csv"))
        .as(DocumentFormat.builder()
                .from(DefaultDocumentFormatRegistry.CSV)
                .loadProperty("FilterOptions", "44,34,0,1,1/2")
                .build())
        .to(new File("C:\\temp\\sample_csv\\out.pdf"))
        .execute();
```
You may want to cache the created DocumentFormat instead of creating a new one for each conversion.

**Comment by sbraconnier** [comment]
Did you succeed ??

**Comment by sbraconnier** [comment]
Closing this one since I didn't received any feedback. Feel free to re-open if required.

**Comment by phoekoby** [comment]
I have same problem with convertation of csv file
Source:
[example_quotes_escaped.csv](https://github.com/jodconverter/jodconverter/files/14279551/example_quotes_escaped.csv)
Result:
[example_quotes_escaped.pdf](https://github.com/jodconverter/jodconverter/files/14279555/example_quotes_escaped.pdf)

I tried to use your code:
```
converter
        .convert(new File("C:\\temp\\sample_csv\\sample_csv.csv"))
        .as(DocumentFormat.builder()
                .from(DefaultDocumentFormatRegistry.CSV)
                .loadProperty("FilterOptions", "44,34,0,1,1/2")
                .build())
        .to(new File("C:\\temp\\sample_csv\\out.pdf"))
        .execute();
```
