### ISSUE TITLE
Some problem happens when convert xlsx to pdf

### ISSUE THREAD

**Issue by XuSen1210** [sbraconnier/jodconverter#226]
I try to convert xlsx to pdf but got this problem.
![image](https://user-images.githubusercontent.com/48204616/93074036-622fc500-f6b6-11ea-81e6-84836beb3176.png)
The original file is 
[xlsx.xlsx](https://github.com/sbraconnier/jodconverter/files/5217756/xlsx.xlsx)
How can I fix this? I want to hold text in excel cell but it is overstep the boundary。

**Comment by sbraconnier** [comment]
Before I start looking into this, did you try to convert your xlsx file without jodconverter?? I you can do what you want manually (without jodconverter), then you should be able to do it with jodconverter. If not, you will have to report the problem to LibreOffice, and not here, since I do not work on the LibreOffice project itself.

I tried to di it manually here, but I'm not sure of the expected result!

**Comment by sbraconnier** [comment]
Closing this one (no feedback). Feel free to re-open if required.
