### ISSUE TITLE
DocUpdateMode not working?

### ISSUE THREAD

**Issue by JaxCoder** [sbraconnier/jodconverter#227]
I might be misunderstanding what this option is supposed to do - but I have documents that have references that are no longer valid - however the fields are already filled in. I would like these values to show up in the PDF when I do the conversion. I set readOnly = true, and DocUpdateMode = NO_UPDATE (0), but I still get "Error: Reference Source Not Found". 

Sorry if this is the wrong place to ask about this, I'm not sure if this is a shortcoming of libreOffice or if this is my misunderstanding of the options, or if jodConverter isn't implementing it correctly. 

If i open the file directly in libreOffice, i see the same errors and I can't seem to figure out a way to not show them. However when I open in MS Word, i see the existing values, and only get the Error if i try to "update field".

**Comment by sbraconnier** [comment]
Hi there,

If you have the error without using jodconverter, then I'm afraid you will have to report the problem to the LibreOffice team, not here, since I do not work on the LibreOffice project itself.

Feel free to re-open this issue if they have a workaround and you want to know how to apply this workaround using jodconverter.
