### ISSUE TITLE
Pass Store Properties to RemoteConverter

### ISSUE THREAD

**Issue by bulentkazanci** [sbraconnier/jodconverter#232]
Hi,

First of all, thanks for maintaining such a cool library. When I trying to use the library, I realized that although it is possible to pass store properties and filters to LocalConverter, RemoteConverter doesn't have properties to set those settings. Is there any way to pass that settings to RemoteConverter?

**Comment by sbraconnier** [comment]
He there,

It depends what is your "remote" server implementation ? If it is LibreOffice online, it doesn't support this. If it is is some sort of implementation base on the [REST sample](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest), it only supports the load and store properties. You could take a look [here](https://github.com/sbraconnier/jodconverter/issues/224) to understand how the remote module will pass the arguments to the server. I had a discussion last year with a member of the Libre Office team about that and I was suppose to propose a solution for this, but I didn't found the time to do it just yet.

Now, for the filters feature, I'm afraid it's not supported at all when using the remote module. Depending on the remote server, it may be possible to "hack" something by using custom load/store properties, but you have to be the owner of the server side application (it will never work with LibreOffice online).

**Comment by bulentkazanci** [comment]
I'm running [this docker container](https://www.collaboraoffice.com/code/) and reaching to that container from another application through following code

```
private static OfficeManager getOfficeManager() {
        return RemoteOfficeManager.builder()
                .urlConnection("http://localhost:9980")
                .poolSize(1)
                .taskQueueTimeout(30_000L)
                .taskExecutionTimeout(120_000L)
                .build();
    }

    private static DocumentConverter getConverter() throws OfficeException {
        OfficeManager manager = getOfficeManager();
        manager.start();
        return RemoteConverter.builder().officeManager(manager).build();
    }
````

When I use LocalConverter as following, it supports storeProperties and filterChain
```
        LocalConverter.builder()
                .storeProperties(customProperties)
                .officeManager(officeManager)
                .filterChain(selectorFilter)
                .build();
```

but `RemoteConverter` class doesn't have same properties. The example you provided above still uses `LocalConverter`

**Comment by sbraconnier** [comment]
This container is the official LibreOffice online container. Regardless the method you will use to reach the server, it doesn't support passing query parameters. So you will only be able to execute basic conversions.

**Comment by bulentkazanci** [comment]
Thanks for clarification.

**Comment by sbraconnier** [comment]
I just wanted to add that the [REST sample](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest) I was referring to is an "emulation" of the LibreOffice online container. Somebody has even create a [docker container](https://hub.docker.com/r/eugenmayer/kontextwork-converter) for it.

Using this server implementation instead of the LibreOffice one, you will be able to pass load and store properties.

If you are willing to do the same as [this project](https://github.com/EugenMayer/officeconverter), you will be in control of the server side and thus, you will be able to accept whatever query parameters you want, in order to support filter features.

Not sure if you want to go there, but I just wanted to clarify that what you want to do is achievable, with a little bit of extra work :)
