### ISSUE TITLE
Open Office template types are missing from the documentformat.json

### ISSUE THREAD

**Issue by benelot** [sbraconnier/jodconverter#24]
Since the conversion can also start from the template types of open office, the types should also be included. I added at least the OTT in my local version of your code.

**Comment by sbraconnier** [comment]
Thank you so much for your feedback. Since you seem to have spent some time to search for the filter that represents a template as source document, could you please hint me on what should be added to [this file](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/resources/document-formats.json).

Note: About the supported formats (conversions), you don't need to "extend" this project. You can specify a custom document format registry.

Here's an (untested) example:

```java
JsonDocumentFormatRegistry customRegistry = JsonDocumentFormatRegistry.create(some file or input stream containing the document formats you want to support);

final File inputFile = ...
final File outputFile = ...

LocalConverter
  .builder()
  .formatRegistry(customRegistry)
  .build()
  .convert(inputFile)
  .to(outputFile)
  .execute();
```

**Comment by sbraconnier** [comment]
I've merged your PR after changing it a bit to use the proper storage template filter types.

I also added the ability to disable OpenGL for LibreOffice (don't know why but once in a while, when converting a template... boom... LO crashes. Apache Open Office does not).

Let me know if everything still works fine on your side, so that this issue could be closed.

**Comment by benelot** [comment]
Oh, that is interesting. So you get crashes when converting templates too?
We experience this problem as well and I do not know the reason at all yet.
I will check if your solution fixes our problem as well. Thx!

**Comment by sbraconnier** [comment]
OpenGL was not properly disabled prior to this [commit](https://github.com/sbraconnier/jodconverter/commit/301ce540f142d4332f11c60da5f0c3c801253714) I made this morning, so you may have to update your fork with my latest changes. Disabling OpenGL solved the problems I had with ott files. But I still have some troubles with otp files. Not sure if you just need to convert ott files.

Note that changing the OpenGL setting requires a LibreOffice restart (which JODConverter takes care of).   

Another thing you could try is to set the [templateProfileDir](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) to a path of a (copy of a) user directory you would have configured with the best settings for your conversions. If you disable OpenGL this way (the option is in the Tools / Options / LibreOffice -> View menu item), it won't require a LibreOffice restart.

Here on my Windows, after settings LibreOffice to suit my needs, I copied the directory `C:\Users\myUser\AppData\Roaming\LibreOffice\4` elsewhere (to act as a template profile directory that won't change) set the templateProfileDir to this copy.

It works without any crash, even for otp files!

**Comment by benelot** [comment]
I am thinking about using template user settings anyway, since we have problems with using the user settings that come with a fresh libreoffice portable on different machines. So your hint might give us a much better experience.
