### ISSUE TITLE
LibreOffice Portable support for Windows

### ISSUE THREAD

**Issue by benelot** [sbraconnier/jodconverter#28]
We recently switched to LibreOffice Portable to easily distribute LibreOffice with our software. Now I realized that LibreOffice Portable works a little differently. Therefore I took your source and started to modify it for the support. However, I am sure I do it a bit too much quick and dirty. If I told you what the significant differences are, could you help me to find the places where I should apply those changes to contribute back to you?

The differences are:

- You need to start LibreOfficePortable from the LibreOfficePortable.exe (that can be solved by somehow detecting that the officepath is within a libreofficeportable, then it uses a different executable path which points to the LibreOfficePortable.exe)
- On close, it is important that the JODConverter does not close the LibreOfficePortable.exe, since that is only a wrapper. So it needs to close a different process than the one it opened, which is either the soffice.exe or the soffice.bin (the soffice.bin seems to work better, but we did not test that extensively yet).

**Comment by sbraconnier** [comment]
hmmm interesting...

I never used LibreOffice Portable so I installed it to see how it works.

I successfully ran my unit tests using the officeHome settings of an office manager:

```java
OfficeManager officeManager = LocalOfficeManager.builder().officeHome("C:\\tmp\\LibreOfficePortable\\App\\libreoffice").install().build();
officeManager.start();
```

Is it really necessary to start the wrapper LibreOfficePortable.exe executable ?? JODConverter only needs to start the libre office app in order to convert documents.... but maybe there is something I don't get.

**Comment by javydreamercsw** [comment]
I believe the PortableApps executable does some magic under the hood like using letter drive at run time, etc.

On his scenario you should be able to use the real exe files.

**Comment by benelot** [comment]
If you use libreoffice without the portable wrapper, it runs into problems with portability since it seems to look for the wrong folders in several locations. Especially LO portable´s idea to use the special Data folder next to the application does not work, which is very helpful. Also we experienced a lot of crashes when not using the portable.exe. The problem seems to come from settings which are available when you install libreoffice but not when you did not install it. LibreOfficePortable provides these settings in a different location, but you need to use the wrapper then.

**Comment by sbraconnier** [comment]
Thanks for the details.

I did some tests today in order to understand how the wrapper works. A quick solution would be to check if there is a LibreOfficePortable.exe in the specified office home path when [we search for an office process](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/office/LocalOfficeUtils.java#L199) and return it if there is one.

But then the LibreOfficePortable executable is responsible to start the real office process, and this means that we must wait a while before trying to retrieve the office process PID after the LibreOfficePortable process is started. Adding a 1 second sleep right before [this line](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/office/OfficeProcess.java#L343) seems to do the trick, but I didn't test it a lot. This sleep should be apply only when office is started using a LibreOfficePortable executable (not a regular office installation). One way to do this would be to extract [this line](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/office/OfficeProcess.java#L266) from the `prepareProcessBuilder` function (we should use an argument to receive the executable file instead) and you will then be able to check if the executable file is the one requiring a sleep in the `start` function...

Not sure yet it is the right way to go but it is the first that comes in mind.

**Comment by benelot** [comment]
I already could make it work but I am sure that several things I did are
hacks. Are you interested in making JODConverter compatible with the
portable version? If so, I can post the changes here (or add them as a pull
request) and we can look into them how to do it properly. You can then add
comments to the code.

**Comment by sbraconnier** [comment]
I'm interested for sure! Submit your code (here or with a PR, I don't have a preference regarding that) and I'll added it to the project after a full review. Then it will be time to release a version.

**Comment by benelot** [comment]
The changes do not work in case you want to open multiple instances of LibreOfficePortable. I reverted my changes. However, now that we have a proper user settings folder, everything works fine using libreoffice portable distributed with it. You just have to point to %LibreOfficeHome%/App/libreoffice for your officehome and everything should work fine. To get a proper user settings folder, we had to start libreoffice.exe --safe-mode to factory reset the user settings. With those settings, LibreOfficeportable is portable even for the JODConverter. With the user settings prepackaged with the installer, LibreOffice Portable was in fact not portable in our environments. We received a lot of ´exception in synchronize´ errors, which are documented to be resolvable so far only by resetting/deleting the user settings. The above description could be serving as a stub for describing how to use JODConverter with LibreOffice portable. I will post back as soon as we have more experience with our latest setup.

So you are ready for a new release! No changes needed.

**Comment by sbraconnier** [comment]
Great news! Thanks to share your experience with us. I'll keep in mind this issue while improving the JODConverter documentation. I should be able to release a version this week.

**Comment by sbraconnier** [comment]
@benelot, I created a new issue #29 for LibreOffice Portable support documentation. Please post your future experiences there if you have anything new to share with us.

Thanks again.

**Comment by benelot** [comment]
Sounds great, I will do that.

**Comment by LyingDoc** [comment]
At present, I use the latest 2.25 of the official portable version to solve the conversion problem. Currently, there is a problem with liunx and the program is not adapted. I think you can refer to this package (https://github.com/ivan-hc/LibreOffice-appimage), which mainly includes the so library.The portable Linux version is not suitable.
