### ISSUE TITLE
Running jodConverter with Springboot

### ISSUE THREAD

**Issue by peterkronenberg** [sbraconnier/jodconverter#291]
I'm having trouble getting this to work with Springboot using jodconverter-spring-boot-starter.  I can inject the OfficeManager bean defined in JodConverterLocalAutoConfiguration, but I'm not sure what to do with it.  If I run something like
```
JodConverter
   .convert(inputFile)
   .to(outputFile)
   .execute();
```
it tells me that an office manager is required.  If I take the injected bean and run `officeManager.start()`, it tells me that the office manager is already started.  I can't see in the code where it gets started.
I'm not clear how I'm supposed to use the bean.

**Comment by peterkronenberg** [comment]
I looked at https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-samples/jodconverter-sample-spring-boot/src/main/java/org/jodconverter/sample/springboot/ConverterController.java, but I'm not clear on what the difference is between jodConverter and DocumentConverter

**Comment by sbraconnier** [comment]
When you are using the `JodConverter` class the way you do, you are accessing an helper class that will recreate an instance of the `LocalConverter` with the default options (port 2002) everytime it is called. But since you are working with Spring Boot, a `LocalConverter` is created (probably with the default options too) on application startup and thus, the port 2002 is already used. When you are working with Spring Boot, you must use the converter that has been created as a bean (and thus injected in your application context).

The `JodConverter` helper class you are using should not bu used in a Spring Boot application (I should made that clear in the doc, thanks for that).
