### ISSUE TITLE
Not possible to execute RemoteConverter with filters

### ISSUE THREAD

**Issue by Cpinto0594** [sbraconnier/jodconverter#300]
Hi, i'm new with this library and i want to replace some macros defined in a DOCX file and then export it as PDF.
I've seen the TextReplacerFilter class but it's not possible to use it with the RemoteConverter, why is that? 
- how can i use it with the RemoteConverter?

Thanks!

**Comment by sbraconnier** [comment]
If fact, you just can't. The reason is because the remote converter has been created to interact with "Collabora Online", which does not support document transformation while converting a document.

The filters (like the `TextReplacerFilter`) requires a LO/OO installation locally, since it's LO/OO that do the job specific to a filter. When you are using the `RemoteConverter`, you are talking to a remote server.

You best bet would be to emulate the LibreOffice online server yourself (see [this example]()https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest) and then use some custom parameters that you could implement on the server-side. Not a trivial task tho...

Good luck.
