### ISSUE TITLE
Multiple conversion simultaneously

### ISSUE THREAD

**Issue by vikram-sewadra** [sbraconnier/jodconverter#37]
How can I configure jodconverter so it can process multiple request without waiting in queue ?

**Comment by sbraconnier** [comment]
By default, JODConverter will start a single office instance, listening for conversion request on port 2002. In order to process more than 1 conversion at the time, you must start multiple office instances.

This behavior can be achieved using the [portNumbers](https://github.com/sbraconnier/jodconverter/wiki/Configuration#1234portnumbersandorcapital_abcdpipenames) configuration:

```java
// This example will use 4 TCP ports, which will cause
// JODConverter to start 4 office processes when the
// OfficeManager will be started.
OfficeManager officeManager =
    LocalOfficeManager.builder()
        .portNumbers(2002, 2003, 2004, 2005)
        .build();
```

The example above shows how to start an office manager that would be able to process 4 conversions at the time. Note that the more office process you start, the more RAM will be consumed by LibreOffice or Apache OpenOffice.

**Comment by vikram-sewadra** [comment]
@sbraconnier Thank you so much for quick and well explained reply. Thanks a lot buddy

**Comment by javydreamercsw** [comment]
This sounds like another thing to add to the documentation if not there already.

**Comment by sbraconnier** [comment]
It is documented, but too briefly I must say.

I added this one to the [FAQ](https://github.com/sbraconnier/jodconverter/wiki/FAQ#table-of-contents)!
