### ISSUE TITLE
Jodconverter and office in different hosts

### ISSUE THREAD

**Issue by SergiusSidorov** [sbraconnier/jodconverter#40]
I have two docker container: one with libreoffice (--headless --accept='socket,host=0,port=8997,tcpNoDelay=1;urp;') and another one with java server application with jodconverter. How can I configure OfficeManager to interoperate with office in another container?
As I understand, LocalOfficeManager works only with office on localhost. I try to use OnlineOfficeManager, but conversion failed by timeout.

**Comment by sbraconnier** [comment]
The JODConverter online module is intended to be use with Collabora Online / LibreOffice Online.

See [LibreOffice Online wiki page](https://github.com/sbraconnier/jodconverter/wiki/LibreOffice-Online) for more details.

Maybe your use case would benefit from using LibreOffice Online ??

**Comment by SergiusSidorov** [comment]
Thank you for quick response. I looked at LOO, but this is too much for my needs. I do not need his capabilities. While it takes too much memory: 500+MB (for comparison: soffice headless takes 40+MB).
It would be nice to be able to work with the remote office service.

**Comment by sbraconnier** [comment]
You could take a look at how the former [ExternalOfficeManager](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/office/ExternalOfficeManager.java) is implemented (you will want to build a connect string that will communicate with the remote office instead of 127.0.0.1), but using this kind of manager doesn't provide office process management (instance pooling, restart on failure, etc.) and I'm not sure if this will work for your use case (never tested it).

You could also start the remote office server as a Web Application inspired by lets say the [Spring Boot Sample projet](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-spring-boot) and change the [ConverterController](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-samples/jodconverter-sample-spring-boot/src/main/java/org/jodconverter/sample/springboot/ConverterController.java) so that it would listen for request using the same path as LibreOffice Online do ( /lool/convert-to/{convertToExt} ), and then use the jodconverter-online module to talk to this server.

But you will still have a bigger footprint (300+MB) for your remote office server.

**Comment by aman048** [comment]
I also use the online module.
I have some problems:
1、when get the response is too large, I get the error：
 Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 2859023; received: 1502340
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1488)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1465)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1440)
	at org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:1442)
	at org.jodconverter.task.OnlineConversionTask.execute(OnlineConversionTask.java:86)

2、I try to use 
 OnlineConverter.make(officeManager).convert(inputStream)
         .as(DefaultDocumentFormatRegistry.XLS)
         .to(outputStream)
         .as(DefaultDocumentFormatRegistry.ODS)
         .execute();
and it get the outputStream is empty. 
Whether OnlineConversionTask.java will call  target.onComplete(targetFile) ?

3、the maven repository is not updated.

**Comment by sbraconnier** [comment]
> 1、when get the response is too large, I get the error：
> Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 2859023; received: 1502340

Are you using a LibreOffice Online installation? Premature connection closed errors are usually attributed to problems in the network (or the server) that can cause the connection to be closed unexpectedly before the entire object is downloaded. Can you please be more specific about your setup (LO Online version and configuration, OS, etc) ?

> 2、I try to use
> OnlineConverter.make(officeManager).convert(inputStream)
> .as(DefaultDocumentFormatRegistry.XLS)
> .to(outputStream)
> .as(DefaultDocumentFormatRegistry.ODS)
> .execute();
> and it get the outputStream is empty.
> Whether OnlineConversionTask.java will call target.onComplete(targetFile) ?

It seems to be a bug, I'll open a new issue for this, thanks.

> 3、the maven repository is not updated.

The jodconverter-online module is pretty much new! I've added SSL support since the last version but I didn't have any feedback from the community about this module and if it really helps people. Now that I know people will use it, I'll try to fix your current issues and then will release a new version.
