### ISSUE TITLE
Use of Spring 5 with Spring Boot 1.x is unusual

### ISSUE THREAD

**Issue by snicoll** [sbraconnier/jodconverter#54]
Rather than having a dependency management for Spring and Spring Boot separately, could you please just align and use Spring Boot's dependency management instead? Spring Boot 2.0 GA is around the corner now with proper integration with Spring Framework 5.

Thanks

**Comment by sbraconnier** [comment]
Thanks! JODConverter now uses the same dependencies for Spring and Spring Boot.

Since the org.apache.httpcomponents:httpclient dependency is provided by Spring Boot, it would be nice if the org.apache.httpcomponents:fluent-hc was provided too, since it uses the same version as httpclient (same as httpmime, which is provided by Spring Boot).

Should I open an issue for this in the Spring Boot project or just submit a pull request?

**Comment by snicoll** [comment]
> Should I open an issue for this in the Spring Boot project or just submit a pull request?

Please open an issue as I am not sure what the outcome will be. If that's accepted, it's a few lines that we can add ourselves. Thanks!

**Comment by sbraconnier** [comment]
[Done](https://github.com/spring-projects/spring-boot/issues/12107)!
