### ISSUE TITLE
Spring security problems

### ISSUE THREAD

**Issue by Pashulity** [sbraconnier/jodconverter#71]
After conversion successfully executed Spring Security session fails 

I can provide more information if necessary

**Comment by sbraconnier** [comment]
Hi there,

Yes more information would be handy, since jodconverter has nothing to do with Spring Security. It's not even a dependency of jodconverter.

**Comment by sbraconnier** [comment]
Ok...

jodconverter is not the problem here for sure. There's no way it could be the cause of your security context being cleared.

I don't know how you have implemented your security authentication. You could post you security configuration here, but I'm not sure I'll be able to help.

By the way, if you are using the jodconverter-spring-boot-starter, you are not supposed to stop the office manager. It will be stopped automatically on application shutdown.

You can look at these two samples for spring boot integration examples:

- [JODConverter - Sample - Rest API](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest)
- [JODConverter - Sample - Spring Boot](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-spring-boot)

**Comment by sbraconnier** [comment]
Closing this one... JodConverter is not the problem here.
