### ISSUE TITLE
convert Document by libreOffice on remote computer

### ISSUE THREAD

**Issue by dep-darkLonely** [sbraconnier/jodconverter#77]
libreOffice is installed on a remote machine。
I want to convert Document by libreOffice on remote computer。
Jodconvert 2.2.2 only needs to specify IP and start up the corresponding service on the remote machine. but Jodconvert 4.2.0 how should I operate?I need JodConvert-online-4.2.0.jar for operation?

**Comment by sbraconnier** [comment]
This fork was created from [mirkonasato/jodconverter](https://github.com/mirkonasato/jodconverter), which is the version 3.0 of jodconverter from the original author, available [here](https://code.google.com/archive/p/jodconverter/downloads). I don't think it's possible to specify a remote URL with this version since URLs are always built using address 127.0.0.1, according to the original [UnoUrl class](https://github.com/mirkonasato/jodconverter/blob/master/jodconverter-core/src/main/java/org/artofsolving/jodconverter/office/UnoUrl.java).

You could take a look at [Collabora Online](https://www.collaboraoffice.com/code/). The jodconverter-online module is fully compatible with this LibreOffice Online distribution.
