### ISSUE TITLE
General Questions about Terminology and Parameters for the new jodconverter toolset

### ISSUE THREAD

**Issue by KarolBuchta** [sbraconnier/jodconverter#88]
Hi,

we are very happy that you took the effort to maintain the jod-converter toolset. Thank you a lot for the great work!

We are going to migrate from nuxeon jod-converter to your fork in our enterprise application.

We are not sure whether we understood the commands and documentation correctly and have certain questions.

**JOD Converter CLI**
Can the new jod-converter cli tool be used with a remote headless libreoffice? 
There is the -p --port parameter (Office socket port)
And there is the -c, --connection-url, where one can specify a remote server for conversion.
_Question:_
Can the remote server specified in the -c paramater just be a headless LibreOffice? The version in nuxeon we used only allows to specify the socket port and expects a locally executed libre office.

**Libre Office Online VS Libre Office Headless**
As we didn't understand this difference and it applies to other parts of the jod-converter system, we would like to know:
_Question:_
Is libreoffice online just an alias / better name for "libreoffice headless" or is it a completely separate system with a different definition?

**The webapp variant**
_Question:_
If the other assumptions above don't apply for libre office headless: Can the webapp variant talk to a remote libre office headless server?

Please note: If we can make the jod-converter toolset talk to a headless office remotely somehow, we will save a lot work on our site. We assume that this does not work right now, but we want to make sure that this is true. Hence the questions.

Thank you a lot for your time.

**Comment by sbraconnier** [comment]
Hi there. Thanks for your kind words. I'll try to answer your questions the best I can.

First of all, let me explain the general idea behind the jodconverter-online module. In fact, it's just a module that will use a remote [LibreOffice Online](https://www.libreoffice.org/download/libreoffice-online/) installation to execute document conversions. So, when using this module, there is no need to install LibreOffice locally, but you must work with a remote LibreOffice Online [installation](https://freedif.org/libreoffice-5-3-is-out-with-an-online-version). See [here](https://www.collaboraoffice.com/document-conversion/) for an article that compares different solutions. Note that the comparison is done using the jodconverter-cli module (1 conversion at the time), so I consider it not fair because you can start multiple office instances when using JODConverter as an API. 
 So now, here's your anwsers:

> Can the new jod-converter cli tool be used with a remote headless libreoffice?

I'm afraid it can't. It can only be used to talk with a LibreOffice Online installation. Note that I've created a [JODConverter REST API sample](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest) that emulates a LibreOffice online instllation. So the jodconverter-online module can talk to this sample web app.

> Is libreoffice online just an alias / better name for "libreoffice headless" or is it a completely separate system with a different definition?

No. It's the module that can communicate with a LibreOffice Online installation (or the [JODConverter - REST API sample](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest)). If you look at the project dependencies, the jodconverter-local module will need the libraries required to communicate with an office instance (juh, unoil, etc.) and the jodconverter-online module will instead need some httpcomponents libraries to communicate with a remote server.

> If the other assumptions above don't apply for libre office headless: Can the webapp variant talk to a remote libre office headless server?

Sadly, no again! I don't know what your architecture looks like, but if you could just install a webapp (let's  say an improved version of the [JODConverter - REST API sample](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest)) where your remote LibreOffice installation lives, so the web app could use this LibreOffice installation locally, then you would be able to use the jodconverter-online module to talk to this web app (which is just a REST API answering conversion request).

If you have any more questions, don't hesitate. See [here](https://github.com/sbraconnier/jodconverter/wiki) for the "work in progress not fast enough" documentation :)

**Comment by EugenMayer** [comment]
@sbraconnier first, thank you for taking so much time to answer all those questions. Very appreciated!

I am a colleague of @KarolBuchta and currently taking over the work here - just for your understanding.

----

I try to rephrase what i understood in own words so you can measure if a messed it up (again) :)

a) Libreoffice-Online = libreoffice-headless + jodconverter-rest (https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest )
So basically exposing libreoffice-headless with an REST interface, but calling libreoffice using the socket internally. So that means its not a "libreoffice native rest interface", its rather a REST interface by jodconverter, wrapping the internal libreoffice interface ( which runs on the same machine )

Is that about right? Thanks!

b) We can modify our architecture to whatever is needed, we are using docker containers anyway, so we can bundle it any particular ways. What we are just trying to understand is, if we actually still going to use jodconverter-cli or rather using the REST api directly - this would remove the need of SSH access to the converter-server. If my understanding in a) fits, we are able to go the REST-api way by bundling a libreoffice headless with jodconverter into a Docker image.

-----

Are you interested in us doing b) in public so you can use that as an example / groundwork / 
 we can contribute / whatever or is there any work done on this already.

Thank you for your time!

**Comment by sbraconnier** [comment]
> a) Libreoffice-Online = libreoffice-headless + jodconverter-rest (https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest )
> So basically exposing libreoffice-headless with an REST interface, but calling libreoffice using the socket internally. So that means its not a "libreoffice native rest interface", its rather a REST interface by jodconverter, wrapping the internal libreoffice interface ( which runs on the same machine )
> 
> Is that about right? Thanks!

Yes, it's right. The only thing I want to clarify is that it is jodconverter that is responsible to start libreoffice instances in headless mode. But I guess you know that if you are familiar with the nuxeo branch of jodconverter.

> b) We can modify our architecture to whatever is needed, we are using docker containers anyway, so we can bundle it any particular ways. What we are just trying to understand is, if we actually still going to use jodconverter-cli or rather using the REST api directly - this would remove the need of SSH access to the converter-server. If my understanding in a) fits, we are able to go the REST-api way by bundling a libreoffice headless with jodconverter into a Docker image.

I would definitely go with the REST Api way. The jodconverter-cli module will launch a libreoffice instance each time it is executed. A web app (REST Api) will launch, on start, as many libreoffice instances as [port numbers](https://github.com/sbraconnier/jodconverter/wiki/Configuration#1234portnumbersandorcapital_abcdpipenames) configured. Since your REST Api would probably use the jodconverter-spring-boot-starter (as the [jodconverter-sample-rest](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest) do), you can take a look at [this class](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-spring-boot-starter/src/main/java/org/jodconverter/boot/autoconfigure/JodConverterLocalProperties.java) for a complete list of available configuration options for a webapp (regarding jodconverter).

Don't forget that the sample app is just a sample, not tested intensively and not running over https! But if you are familiar with spring boot, it would not required a lot of work to make it production ready.

>Are you interested in us doing b) in public so you can use that as an example / groundwork /
we can contribute / whatever or is there any work done on this already.

I would love that! I'm not familiar with Docker so for me trying to do something similar would be a lot of tutorials before even starting to think about it :). You can contribute the way you want (new samples, documentation, links to your repository I could add to the wiki, even a new module!). Any contribution that improves this project is welcome.

>Thank you for your time!

You're welcome!

**Comment by EugenMayer** [comment]
@sbraconnier thank you once again.

One last question would be, can we reduce the amount of packages we need. Can we go with calc/writer for a converter or do we need the whole meta-package?

**Comment by sbraconnier** [comment]
> One last question would be, can we reduce the amount of packages we need. Can we go with calc/writer for a converter or do we need the whole meta-package?

I guess it could be, but I never tested this scenario. You could test it using the [jodconverter-cli](https://github.com/sbraconnier/jodconverter/releases/download/v4.2.0/jodconverter-cli-4.2.0.zip) module. If you can use the cli module to properly execute conversion with a libreoffice installation that contains only the calc and writer package, then it would also work using jodconverter.

Maybe the jodconverter-online module name is a bit confusing. I used that name to indicate that it works with LibreOffice Online. In fact, it is a client module! It consumes the online Rest Api.

So, to answer your question, the difference between [jodconverter-online](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-online) and [jodconverter-sample-rest](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest]) is that the first one (online) is the client, and the second one (sample-rest) the server. The client (online) will send conversion requests to the server (sample-rest). LibreOffice has only to be installed where the sample-rest is installed, but is not required where the client (online) is installed.

The online module has been initially developped and tested using [Collabora Online Development Edition](https://www.collaboraoffice.com/code/). I later developped the jodconverter-sample-rest sample to demonstrate how we could develop our own REST-Api server.  See [here](https://github.com/sbraconnier/jodconverter/issues/41#issuecomment-359999597) if you want to know exactly why I created this sample project (REST Api).

**Comment by EugenMayer** [comment]
Thanks.

Ok enough of the talking so this is the project for now: https://github.com/EugenMayer/docker-image-jodconverter

You can start it using

    

More details:
- we package on openjdk:10 server-jre to have proper docker support  https://github.com/EugenMayer/docker-image-jodconverter/blob/master/Dockerfile#L2 and using the debian sid libreoffice which is 6.1.1.2 for now https://github.com/EugenMayer/docker-image-jodconverter/blob/master/Dockerfile#L7

- jodconverter-springboot-example is build using openjdk:10-jdk https://github.com/EugenMayer/docker-image-jodconverter/blob/master/Dockerfile#L10 using `gradle build` and extracted the `.war` file

- our runtime container uses the libreoffice image we build before and includes the build artifact from our buildstep before https://github.com/EugenMayer/docker-image-jodconverter/blob/master/Dockerfile#L23 and simply runs it for now https://github.com/EugenMayer/docker-image-jodconverter/blob/master/Dockerfile#L24

So its a very simple build (multistage build) with a fairly clean libreoffice + jodconverter runtime.

**Comment by sbraconnier** [comment]
Wow!! Thank you so much! Good work and great explanation!

I see that you're [planning on doing the same](https://github.com/EugenMayer/docker-image-jodconverter/issues/3) with the REST-Api sample, which would be great!

I'll create a wiki page linking to your repository. Thanks!

**Comment by EugenMayer** [comment]
@sbraconnier thanks! Yes REST version is undergo, but with issues on that https://github.com/EugenMayer/docker-image-jodconverter/issues/3 - you have any idea? Do i run the wrong build task? https://github.com/EugenMayer/docker-image-jodconverter/blob/master/Dockerfile#L27

**Comment by EugenMayer** [comment]
I spinned of a new REST project based on your work of course, with a little more production scope and also support for conversion of HTML file. I will most probably add "outputFolder" support and or / zip support to bundle the assets, if they are more then one ( simple case with all then html+pictures ).
I started to use Services as you obviously already "planned" or advised for production use and try to keep it a clean implementation AFAIC. I also want to make the production build "swagger less" on all those kind of things which might be just over the top for the "example". If you want, i create an issue here for a brief discussion how we should go with that.

 I specifically build on top of your REST example which is a perfect tool!

https://github.com/EugenMayer/converter

For now, i keep this separated from this repo but we can for sure discuss anything around that. The point will be.

some findings for now maybe interesting for this repo but i was not sure where to patch this in a PR, so i go with all those i am not sure how to PR here:

- https://github.com/EugenMayer/converter/blob/master/build.gradle#L44
This is needed to avoid reflection errors with J9/J10
- Should we rather go with @RestController instead of @Controller or did you plan something with that?

**Comment by sbraconnier** [comment]
Haha ! Just Wow!! Great work!!!

I didn't use the @RestController annotation since it's just the regular @Controller + @ResponseBody annotations, and that our controller has only 1 method returning a ResponseEntity. So it doesn't make any difference here to use @RestController instead of @Controller. But it doesn't hurt either! 

Don't bother creating PR for this. I could just create a link to your project in the README file of the sample Rest API project!
