### ISSUE TITLE
Handling HTML output format

### ISSUE THREAD

**Issue by EugenMayer** [sbraconnier/jodconverter#92]
I am currently testing the HTML output format which is special compared to (all/most) the others. It seems like the converter expects one output file in general, but this is not true for html conversion if pictures are included.

The HTML file then references pictures which are saved in the working temp folder by the office conversion job.

I am not sure what is the best way to go with that. We could:
 
## Strategy a)
Let the jodconverter handle this case:
In this case, we would handle the HTML case with a custom logic in jodconverter by:
 - if HTML is the outputDocumentFormat, parse the XML, pick out all `img` tags and its src attribute (path). Now open a filestream to that file ( in the temp folder ) and then read it, convert it to base64 with the correct file extension and put it into the HTML. Do that for every img inside the HTML.
Then return the HTML file with the blobs included. This way we need no other interface in DocumentConverter::convert and we can still keep one `OutputStream` - so we hide the special case.
Extra hint: from time to time, i am yet not sure about the creteria, LO puts some pictures into the content using Base64 by default - but its rare.

## Strategy b)
Basically a) but we find an extra option to call LO with, to enforce all images being base64 encoded by default. We put that as a spring configuration, which is yet "off" by default ( to keep it backwards compatible )

Maybe references: 
- https://ask.libreoffice.org/en/question/31382/how-to-deactivate-embedding-images-in-html-file-42/
- https://stackoverflow.com/a/32914804

Seems like it was changed from default to optional according to https://bugs.documentfoundation.org/show_bug.cgi?id=48887#c60 .. the question is, which option :)

## Strategy c)
We change the interface or at least, we make it possible for the caller to find the temp folder (well yet, we give a `working_dir` but jodconverter will create a new folder inside there `jodconverter_05ca526d-c945-4eef-bee1-79a9f1622530` (random, i guess per LO instance) and thus we cannot really guess it.

OfficeManager has `tempDir` but its private, which actually points to that folder and also has a list of files this directory currently includes.

Its then up to the caller to parse the HTML file, pick up the images from the temp folder and then handle that case.

---
a) or b) i would assume would be the best assuming that jodconverter wants to be that "unified" interface for the LO conversion chain.

**Comment by EugenMayer** [comment]
If we are going to implement an option for Strategy b) i guess it would be somewhere here https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/task/LocalConversionTask.java#L85 more specifically https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/task/LocalConversionTask.java#L162 ...

I see that those "storeOptions" are available, which are also part of LocalConverter builder https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/LocalConverter.java#L278 ... so i guess the option one could find for HTML would be already "possible to implement" by the caller. If there is an option.

Any idea how to look up the available options?

**Comment by EugenMayer** [comment]
Well, it seems thats the cli option https://ask.libreoffice.org/en/question/88061/option-to-embed-images-in-generated-html-file/?answer=88109#post-id-88109 .. but i am not sure how to reverse engineer that to a UnoRuntime option

**Comment by EugenMayer** [comment]
Seems like we might have to add a new target format next to https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/resources/document-formats.json#L34 .. so html:embedded and then pick the right filter i guess. Which one i am not able to find right now

**Comment by EugenMayer** [comment]
I guess that is at least a reference what can be put into the properties: https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1document_1_1MediaDescriptor.html

**Comment by EugenMayer** [comment]
I think we have it: https://cgit.freedesktop.org/libreoffice/online/commit/?id=7e9ba2e8c68f6904177272bee9453860224174ec .. so its a FilterOption 'EmbedImages'

**Comment by EugenMayer** [comment]
I tested #93 and it actually worked as expected, images are now embedded as base64. Considering that lool does the same by default, i would actually use this as a default. 

@sbraconnier if you think that this is not expected by people ( i would rather say, considering the current interface, people might see this multi-file export as a bug rather ) ..  we could use a new export format defintion instead like html:embedded or something like that. But we would then differ from the actual lool implementation

**Comment by sbraconnier** [comment]
I'm sorry, I wasn't available today! I could have saved you a lot of time since this problem has already been discussed here #41 and here #47.

I was the one that opened a bug report ([117077](https://bugs.documentfoundation.org/show_bug.cgi?id=117077)) at LO Online to inform them that images should be embedded by default when converting to HTML. It wasn't the case initially.

I never thought to enforce this option though. But my opinion is that it should be!! So I will probably merge #93 but I want to take a deeper look at it first. Since it would be a breaking change,  The next jodconverter version would be 4.3.0.

**Comment by EugenMayer** [comment]
@sbraconnier no worries, you do not need to do my job :)

We could go 4 ways here:

1. implement it as the default like #93 is doing
2. implement the "embedd" variant as own DocumentFormat "html:embedded" and keep the default on non-embedded
3. we could implement 1 and offer 2) inversed, so the variant without embedding like html:linked
4. We could offer a option of the officeManager / in spring boot to define the default

If 4 is an idea, i am not sure how to "on the fly" modify an existing Filter - could you think about how to do that? just add some store options with the same name and they get merged? I know we can add options, but this would be an option "for a specific filter".
To workarround this complexity would could implement 2 and 4 together, making the switch for "which DocumentFormat to choose when html is given"

What do you think?

**Comment by EugenMayer** [comment]
@sbraconnier i am trying to build https://github.com/EugenMayer/converter against a custom snapshot build of jodconverter right now

1. used ./gradlew build to build the project
2. copied this under libs
![image](https://user-images.githubusercontent.com/136934/45963165-d59c2000-c022-11e8-84b7-063df4dc56bb.png)
3. `compile fileTree(dir: 'libs', include: ['*.jar'])` under dependencies. During runtime though i get  a lot of Class not found execptions, seems like all the dependencies of -core are missing ` org.apache.commons.lang3.StringUtils` if i include commons, i get lang, if i include lang we get to the next.

Could you explain how i would probably build a custom version of jodconverter for now (https://github.com/EugenMayer/jodconverter/tree/fix/html-export-embedd-images) to link the `converter` project against it?

**Comment by sbraconnier** [comment]
Hi there! I didn't want to close this issue. I'm not sure why merging #93 did that! So to anwser you previous posts:

> We could go 4 ways here:
> 1. Implement it as the default like #93 is doing
> 2. Implement the "embedd" variant as own DocumentFormat "html:embedded" and keep the default on non-embedded
> 3. We could implement 1 and offer 2) inversed, so the variant without embedding like html:linked
> 4. We could offer a option of the officeManager / in spring boot to define the default

I'm not a fan of 2 and 3 because the output format can be auto-detected according to the output filename extension. Thus, a file extension cannot represent more that 1 filter.

I've decided to merge #93 for now but I may change my mind before the next release. I cannot really know the impact on all the jodconverter users, even if it seems logical to me to always embedding images!

Maybe the best solution would be 4, but instead of a new option, we could just add a property to the spring-boot-starter that will allow the application to have its own document-formats.json, since it is supported by JodConverter. When you create a converter like it is done [here in your project](https://github.com/EugenMayer/converter/blob/master/src/main/java/de/kontextwork/converter/service/ConverterService.java#L31), you can specify the [DocumentFormatRegistry](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/java/org/jodconverter/document/DocumentFormatRegistry.java) that will be used for the conversions through the [formatRegistry](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/java/org/jodconverter/job/AbstractConverter.java#L150) property of the builder. When not specified, it default to the [DefaultDocumentFormatRegistry](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/java/org/jodconverter/document/DefaultDocumentFormatRegistry.java), which is a singleton class that loads the document-formats.json on first use.
 
I'm very busy this week so this change will probably wait for next week. But I've publish a SNAPSHOT version that contains #93 to help you with your build!

Here's the maven repo where the snapshot is published:
https://oss.sonatype.org/content/repositories/snapshots/

**Comment by EugenMayer** [comment]
Thank you @sbraconnier - very reasonable decision and also with the option of 4. Thanks for the snapshot!

**Comment by sbraconnier** [comment]
I'll close this issue. You can track #94  instead.
